version: 2.1

executors:
  clojure-tools-deps:
    docker:
    - image: circleci/clojure:openjdk-11-tools-deps-1.10.3.998
jobs:
  ci:
    executor: clojure-tools-deps
    steps:
      - checkout
      - run:
          name: Run build and test
          command: clojure -T:build ci

  deploy-clojars:
    executor: clojure-tools-deps
    steps:
      - checkout
      - run:
          name: Deploy to Clojars
          command: clojure -T:build deploy

workflows:
  build-test-publish_clojars:
    jobs:
      - ci:
          filters:
            tags:
              only: /.*/
      - deploy-clojars:
          context: clojars
          requires:
            - ci
          filters:
            tags:
              only: /^[0-9].*/
            branches:
              ignore: /.*/
